export interface Props {
	background?: string;
	backgroundColor?: string;
	backgroundImage?: string;
	backgroundPosition?: string | number;
	backgroundSize?: string | number;
	backgroundOrigin?: string | number;
	backgroundRepeat?: string;
	backgroundClip?: string;
	backgroundBlendMode?: string;
	borderBottomLeftRadius?: string | number;
	borderBottomRightRadius?: string | number;
	borderTopLeftRadius?: string | number;
	borderTopRightRadius?: string | number;
	borderRadius?: string | number;
	border?: string;
	borderBottom?: string;
	borderBottomColor?: string;
	borderBottomStyle?: string;
	borderBottomWidth?: string | number;
	borderColor?: string;
	borderLeft?: string;
	borderLeftColor?: string;
	borderLeftStyle?: string;
	borderLeftWidth?: string | number;
	borderRight?: string;
	borderRightColor?: string;
	borderRightStyle?: string;
	borderRightWidth?: string | number;
	borderStyle?: string;
	borderTop?: string;
	borderTopColor?: string;
	borderTopStyle?: string;
	borderTopWidth?: string | number;
	borderWidth?: string | number;
	shadow?: string;
	height?: string | number;
	maxHeight?: string | number;
	maxWidth?: string | number;
	minHeight?: string | number;
	minWidth?: string | number;
	width?: string | number;
	alignContent?: string;
	alignItems?: string;
	alignSelf?: string;
	flex?: string | number;
	flexBasis?: string | number;
	flexDirection?: string;
	flexFlow?: string;
	flexGrow?: string | number;
	flexShrink?: string | number;
	flexWrap?: string;
	justifyContent?: string;
	justifyItems?: string;
	justifySelf?: string;
	order?: string | number;
	placeContent?: string;
	placeItems?: string;
	placeSelf?: string;
	cursor?: string;
	pointerEvents?: string;
	userSelect?: string;
	visibility?: string;
	boxSizing?: string;
	clear?: string;
	clearfix?: boolean;
	display?: string;
	float?: string;
	zIndex?: string | number;
	listStyle?: string;
	listStyleType?: string;
	listStyleImage?: string;
	listStylePosition?: string;
	opacity?: string | number;
	overflow?: string;
	overflowX?: string;
	overflowY?: string;
	bottom?: string | number;
	left?: string | number;
	position?: string;
	right?: string | number;
	top?: string | number;
	margin?: string | number;
	marginBottom?: string | number;
	marginLeft?: string | number;
	marginRight?: string | number;
	marginTop?: string | number;
	marginX?: string | number;
	marginY?: string | number;
	padding?: string | number;
	paddingBottom?: string | number;
	paddingLeft?: string | number;
	paddingRight?: string | number;
	paddingTop?: string | number;
	paddingX?: string | number;
	paddingY?: string | number;
	color?: string;
	font?: string;
	fontFamily?: string;
	fontSize?: string | number;
	fontStyle?: string;
	fontVariant?: string;
	fontWeight?: string | number;
	letterSpacing?: string | number;
	lineHeight?: string | number;
	textAlign?: string;
	textDecoration?: string;
	textOverflow?: string;
	textShadow?: string;
	textTransform?: string;
	whiteSpace?: string;
	wordBreak?: string;
	wordWrap?: string;
	transform?: string;
	transformOrigin?: string;
	transition?: string;
	transitionDelay?: string;
	transitionDuration?: string;
	transitionProperty?: string;
	transitionTimingFunction?: string;
}
